2024-06-30 10:03:28,069 INFO    MainThread:32724 [wandb_setup.py:_flush():76] Current SDK version is 0.17.3
2024-06-30 10:03:28,069 INFO    MainThread:32724 [wandb_setup.py:_flush():76] Configure stats pid to 32724
2024-06-30 10:03:28,069 INFO    MainThread:32724 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Wen-Liang\.config\wandb\settings
2024-06-30 10:03:28,069 INFO    MainThread:32724 [wandb_setup.py:_flush():76] Loading settings from E:\huggingface_ex\wandb\settings
2024-06-30 10:03:28,069 INFO    MainThread:32724 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-06-30 10:03:28,069 INFO    MainThread:32724 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-06-30 10:03:28,070 INFO    MainThread:32724 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'Phi3-Vision.py', 'program_abspath': 'E:\\huggingface_ex\\Phi3-Vision.py', 'program': 'E:\\huggingface_ex\\Phi3-Vision.py'}
2024-06-30 10:03:28,070 INFO    MainThread:32724 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-06-30 10:03:28,070 INFO    MainThread:32724 [wandb_init.py:_log_setup():520] Logging user logs to E:\huggingface_ex\wandb\run-20240630_100328-ylejexp4\logs\debug.log
2024-06-30 10:03:28,070 INFO    MainThread:32724 [wandb_init.py:_log_setup():521] Logging internal logs to E:\huggingface_ex\wandb\run-20240630_100328-ylejexp4\logs\debug-internal.log
2024-06-30 10:03:28,070 INFO    MainThread:32724 [wandb_init.py:init():560] calling init triggers
2024-06-30 10:03:28,070 INFO    MainThread:32724 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-06-30 10:03:28,070 INFO    MainThread:32724 [wandb_init.py:init():610] starting backend
2024-06-30 10:03:28,070 INFO    MainThread:32724 [wandb_init.py:init():614] setting up manager
2024-06-30 10:03:28,073 INFO    MainThread:32724 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-06-30 10:03:28,074 INFO    MainThread:32724 [wandb_init.py:init():622] backend started and connected
2024-06-30 10:03:28,079 INFO    MainThread:32724 [wandb_init.py:init():711] updated telemetry
2024-06-30 10:03:28,115 INFO    MainThread:32724 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-06-30 10:03:28,718 ERROR   MainThread:32724 [wandb_init.py:init():770] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-06-30 10:03:28,718 ERROR   MainThread:32724 [wandb_init.py:init():1181] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Wen-Liang\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 1171, in init
    return wi.init()
           ^^^^^^^^^
  File "C:\Users\Wen-Liang\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-06-30 10:03:30,058 WARNING MsgRouterThr:32724 [router.py:message_loop():77] message_loop has been closed
